
sales_data = {1: {'Transaction_ID': 'NP00001',
     'Date': '2025-03-13',
     'City': 'Lalitpur',
     'Customer_Gender': 'Female',
     'Customer_Age': 52,
     'Product_Category': 'Home & Kitchen',
     'Product_Name': 'Electric Kettle',
     'Quantity': 2,
     'Unit_Price_NPR': 2200,
     'Payment_Method': 'Cash',
     'Sales_NPR': 4400.0,
     'Customer_Type': 'Returning'},
 2: {'Transaction_ID': 'NP00002',
     'Date': '2025-10-15',
     'City': 'Pokhara',
     'Customer_Gender': 'Female',
     'Customer_Age': 52,
     'Product_Category': 'Electronics',
     'Product_Name': 'Smart Watch',
     'Quantity': 1,
     'Unit_Price_NPR': 7500,
     'Payment_Method': 'eSewa',
     'Sales_NPR': 7500.0,
     'Customer_Type': 'Returning'},
 3: {'Transaction_ID': 'NP00003',
     'Date': '2025-08-05',
     'City': 'Biratnagar',
     'Customer_Gender': 'Male',
     'Customer_Age': 31,
     'Product_Category': 'Clothing',
     'Product_Name': 'Kurta Set',
     'Quantity': 2,
     'Unit_Price_NPR': 3200,
     'Payment_Method': 'Bank Transfer',
     'Sales_NPR': 6400.0,
     'Customer_Type': 'New'},
 4: {'Transaction_ID': 'NP00004',
     'Date': '2025-05-16',
     'City': 'Kathmandu',
     'Customer_Gender': 'Female',
     'Customer_Age': 52,
     'Product_Category': 'Electronics',
     'Product_Name': 'Wireless Earbuds',
     'Quantity': 1,
     'Unit_Price_NPR': 2500,
     'Payment_Method': 'Cash',
     'Sales_NPR': 2500.0,
     'Customer_Type': 'Returning'},
 5: {'Transaction_ID': 'NP00005',
     'Date': '2025-07-05',
     'City': 'Hetauda',
     'Customer_Gender': 'Male',
     'Customer_Age': 22,
     'Product_Category': 'Electronics',
     'Product_Name': 'Bluetooth Speaker',
     'Quantity': 2,
     'Unit_Price_NPR': 3200,
     'Payment_Method': 'Cash',
     'Sales_NPR': 6400.0,
     'Customer_Type': 'New'},
 6: {'Transaction_ID': 'NP00006',
     'Date': '2025-07-14',
     'City': 'Bharatpur',
     'Customer_Gender': 'Male',
     'Customer_Age': 41,
     'Product_Category': 'Clothing',
     'Product_Name': 'Kurta Set',
     'Quantity': 2,
     'Unit_Price_NPR': 3200,
     'Payment_Method': 'Cash',
     'Sales_NPR': 6080.0,
     'Customer_Type': 'New'},
 7: {'Transaction_ID': 'NP00007',
     'Date': '2025-05-06',
     'City': 'Bhaktapur',
     'Customer_Gender': 'Male',
     'Customer_Age': 35,
     'Product_Category': 'Home & Kitchen',
     'Product_Name': 'Electric Kettle',
     'Quantity': 1,
     'Unit_Price_NPR': 2200,
     'Payment_Method': 'Bank Transfer',
     'Sales_NPR': 2200.0,
     'Customer_Type': 'Returning'},
 8: {'Transaction_ID': 'NP00008',
     'Date': '2025-04-28',
     'City': 'Kathmandu',
     'Customer_Gender': 'Female',
     'Customer_Age': 43,
     'Product_Category': 'Beauty & Personal Care',
     'Product_Name': 'Sunscreen',
     'Quantity': 2,
     'Unit_Price_NPR': 1100,
     'Payment_Method': 'Cash',
     'Sales_NPR': 2090.0,
     'Customer_Type': 'New'},
 9: {'Transaction_ID': 'NP00009',
     'Date': '2025-11-26',
     'City': 'Butwal',
     'Customer_Gender': 'Male',
     'Customer_Age': 26,
     'Product_Category': 'Books & Stationery',
     'Product_Name': 'Academic Planner',
     'Quantity': 1,
     'Unit_Price_NPR': 650,
     'Payment_Method': 'Cash',
     'Sales_NPR': 650.0,
     'Customer_Type': 'Returning'},
 10: {'Transaction_ID': 'NP00010',
      'Date': '2025-07-05',
      'City': 'Pokhara',
      'Customer_Gender': 'Female',
      'Customer_Age': 26,
      'Product_Category': 'Clothing',
      'Product_Name': 'Jacket',
      'Quantity': 1,
      'Unit_Price_NPR': 5500,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 5500.0,
      'Customer_Type': 'New'},
 11: {'Transaction_ID': 'NP00011',
      'Date': '2025-12-15',
      'City': 'Birgunj',
      'Customer_Gender': 'Female',
      'Customer_Age': 42,
      'Product_Category': 'Electronics',
      'Product_Name': 'Wireless Earbuds',
      'Quantity': 1,
      'Unit_Price_NPR': 2500,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 2500.0,
      'Customer_Type': 'Returning'},
 12: {'Transaction_ID': 'NP00012',
      'Date': '2025-02-28',
      'City': 'Dharan',
      'Customer_Gender': 'Female',
      'Customer_Age': 59,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Body Lotion',
      'Quantity': 2,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 1700.0,
      'Customer_Type': 'New'},
 13: {'Transaction_ID': 'NP00013',
      'Date': '2025-05-15',
      'City': 'Dharan',
      'Customer_Gender': 'Female',
      'Customer_Age': 50,
      'Product_Category': 'Electronics',
      'Product_Name': 'Wireless Earbuds',
      'Quantity': 3,
      'Unit_Price_NPR': 2500,
      'Payment_Method': 'Bank Transfer',
      'Sales_NPR': 7125.0,
      'Customer_Type': 'Returning'},
 14: {'Transaction_ID': 'NP00014',
      'Date': '2025-03-24',
      'City': 'Dharan',
      'Customer_Gender': 'Female',
      'Customer_Age': 51,
      'Product_Category': 'Clothing',
      'Product_Name': 'Jacket',
      'Quantity': 1,
      'Unit_Price_NPR': 5500,
      'Payment_Method': 'Bank Transfer',
      'Sales_NPR': 5500.0,
      'Customer_Type': 'Returning'},
 15: {'Transaction_ID': 'NP00015',
      'Date': '2025-06-07',
      'City': 'Pokhara',
      'Customer_Gender': 'Male',
      'Customer_Age': 54,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 4,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Bank Transfer',
      'Sales_NPR': 3230.0,
      'Customer_Type': 'New'},
 16: {'Transaction_ID': 'NP00016',
      'Date': '2025-03-06',
      'City': 'Bhaktapur',
      'Customer_Gender': 'Female',
      'Customer_Age': 53,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 5,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Cash',
      'Sales_NPR': 4250.0,
      'Customer_Type': 'Returning'},
 17: {'Transaction_ID': 'NP00017',
      'Date': '2025-12-20',
      'City': 'Pokhara',
      'Customer_Gender': 'Female',
      'Customer_Age': 43,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Shampoo',
      'Quantity': 3,
      'Unit_Price_NPR': 750,
      'Payment_Method': 'Bank Transfer',
      'Sales_NPR': 2137.5,
      'Customer_Type': 'Returning'},
 18: {'Transaction_ID': 'NP00018',
      'Date': '2025-02-02',
      'City': 'Biratnagar',
      'Customer_Gender': 'Male',
      'Customer_Age': 53,
      'Product_Category': 'Groceries',
      'Product_Name': 'Wheat Flour 5kg',
      'Quantity': 2,
      'Unit_Price_NPR': 480,
      'Payment_Method': 'Cash',
      'Sales_NPR': 960.0,
      'Customer_Type': 'New'},
 19: {'Transaction_ID': 'NP00019',
      'Date': '2025-06-19',
      'City': 'Lalitpur',
      'Customer_Gender': 'Male',
      'Customer_Age': 35,
      'Product_Category': 'Electronics',
      'Product_Name': 'Wireless Earbuds',
      'Quantity': 1,
      'Unit_Price_NPR': 2500,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 2250.0,
      'Customer_Type': 'New'},
 20: {'Transaction_ID': 'NP00020',
      'Date': '2025-08-31',
      'City': 'Birgunj',
      'Customer_Gender': 'Male',
      'Customer_Age': 24,
      'Product_Category': 'Electronics',
      'Product_Name': 'USB-C Charger',
      'Quantity': 1,
      'Unit_Price_NPR': 1400,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 1400.0,
      'Customer_Type': 'New'},
 21: {'Transaction_ID': 'NP00021',
      'Date': '2025-02-20',
      'City': 'Kathmandu',
      'Customer_Gender': 'Male',
      'Customer_Age': 39,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 3,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Debit Card',
      'Sales_NPR': 2295.0,
      'Customer_Type': 'New'},
 22: {'Transaction_ID': 'NP00022',
      'Date': '2025-05-23',
      'City': 'Butwal',
      'Customer_Gender': 'Male',
      'Customer_Age': 22,
      'Product_Category': 'Clothing',
      'Product_Name': 'Jacket',
      'Quantity': 1,
      'Unit_Price_NPR': 5500,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 5500.0,
      'Customer_Type': 'Returning'},
 23: {'Transaction_ID': 'NP00023',
      'Date': '2025-01-08',
      'City': 'Lalitpur',
      'Customer_Gender': 'Female',
      'Customer_Age': 33,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Face Serum',
      'Quantity': 2,
      'Unit_Price_NPR': 1800,
      'Payment_Method': 'Cash',
      'Sales_NPR': 3600.0,
      'Customer_Type': 'Returning'},
 24: {'Transaction_ID': 'NP00024',
      'Date': '2025-01-02',
      'City': 'Birgunj',
      'Customer_Gender': 'Male',
      'Customer_Age': 47,
      'Product_Category': 'Clothing',
      'Product_Name': 'Cotton T-Shirt',
      'Quantity': 3,
      'Unit_Price_NPR': 1200,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 3600.0,
      'Customer_Type': 'Returning'},
 25: {'Transaction_ID': 'NP00025',
      'Date': '2025-04-08',
      'City': 'Bharatpur',
      'Customer_Gender': 'Male',
      'Customer_Age': 21,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Storage Container Set',
      'Quantity': 2,
      'Unit_Price_NPR': 1600,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 3200.0,
      'Customer_Type': 'Returning'},
 26: {'Transaction_ID': 'NP00026',
      'Date': '2025-09-29',
      'City': 'Bhaktapur',
      'Customer_Gender': 'Male',
      'Customer_Age': 50,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Electric Kettle',
      'Quantity': 1,
      'Unit_Price_NPR': 2200,
      'Payment_Method': 'Cash',
      'Sales_NPR': 2200.0,
      'Customer_Type': 'New'},
 27: {'Transaction_ID': 'NP00027',
      'Date': '2025-10-19',
      'City': 'Pokhara',
      'Customer_Gender': 'Female',
      'Customer_Age': 20,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Shampoo',
      'Quantity': 1,
      'Unit_Price_NPR': 750,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 675.0,
      'Customer_Type': 'Returning'},
 28: {'Transaction_ID': 'NP00028',
      'Date': '2025-12-09',
      'City': 'Biratnagar',
      'Customer_Gender': 'Male',
      'Customer_Age': 43,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Body Lotion',
      'Quantity': 1,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Cash',
      'Sales_NPR': 850.0,
      'Customer_Type': 'Returning'},
 29: {'Transaction_ID': 'NP00029',
      'Date': '2025-10-16',
      'City': 'Lalitpur',
      'Customer_Gender': 'Male',
      'Customer_Age': 31,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 1,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 850.0,
      'Customer_Type': 'New'},
 30: {'Transaction_ID': 'NP00030',
      'Date': '2025-03-22',
      'City': 'Butwal',
      'Customer_Gender': 'Female',
      'Customer_Age': 37,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 4,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 3400.0,
      'Customer_Type': 'Returning'},
 31: {'Transaction_ID': 'NP00031',
      'Date': '2025-12-06',
      'City': 'Lalitpur',
      'Customer_Gender': 'Female',
      'Customer_Age': 26,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Electric Kettle',
      'Quantity': 2,
      'Unit_Price_NPR': 2200,
      'Payment_Method': 'Cash',
      'Sales_NPR': 4400.0,
      'Customer_Type': 'Returning'},
 32: {'Transaction_ID': 'NP00032',
      'Date': '2025-06-25',
      'City': 'Pokhara',
      'Customer_Gender': 'Female',
      'Customer_Age': 34,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Rice Cooker',
      'Quantity': 1,
      'Unit_Price_NPR': 3800,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 3800.0,
      'Customer_Type': 'New'},
 33: {'Transaction_ID': 'NP00033',
      'Date': '2025-05-22',
      'City': 'Kathmandu',
      'Customer_Gender': 'Male',
      'Customer_Age': 26,
      'Product_Category': 'Books & Stationery',
      'Product_Name': 'Notebook Set',
      'Quantity': 1,
      'Unit_Price_NPR': 450,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 450.0,
      'Customer_Type': 'New'},
 34: {'Transaction_ID': 'NP00034',
      'Date': '2025-02-27',
      'City': 'Lalitpur',
      'Customer_Gender': 'Female',
      'Customer_Age': 27,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Storage Container Set',
      'Quantity': 2,
      'Unit_Price_NPR': 1600,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 3200.0,
      'Customer_Type': 'Returning'},
 35: {'Transaction_ID': 'NP00035',
      'Date': '2025-07-06',
      'City': 'Kathmandu',
      'Customer_Gender': 'Female',
      'Customer_Age': 31,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Shampoo',
      'Quantity': 1,
      'Unit_Price_NPR': 750,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 750.0,
      'Customer_Type': 'Returning'},
 36: {'Transaction_ID': 'NP00036',
      'Date': '2025-11-14',
      'City': 'Bhaktapur',
      'Customer_Gender': 'Female',
      'Customer_Age': 33,
      'Product_Category': 'Groceries',
      'Product_Name': 'Wheat Flour 5kg',
      'Quantity': 4,
      'Unit_Price_NPR': 480,
      'Payment_Method': 'Credit Card',
      'Sales_NPR': 1920.0,
      'Customer_Type': 'Returning'},
 37: {'Transaction_ID': 'NP00037',
      'Date': '2025-06-20',
      'City': 'Birgunj',
      'Customer_Gender': 'Female',
      'Customer_Age': 33,
      'Product_Category': 'Sports & Fitness',
      'Product_Name': 'Dumbbell Set',
      'Quantity': 1,
      'Unit_Price_NPR': 4200,
      'Payment_Method': 'Cash',
      'Sales_NPR': 3990.0,
      'Customer_Type': 'Returning'},
 38: {'Transaction_ID': 'NP00038',
      'Date': '2025-08-24',
      'City': 'Biratnagar',
      'Customer_Gender': 'Male',
      'Customer_Age': 32,
      'Product_Category': 'Electronics',
      'Product_Name': 'Wireless Earbuds',
      'Quantity': 2,
      'Unit_Price_NPR': 2500,
      'Payment_Method': 'Cash',
      'Sales_NPR': 5000.0,
      'Customer_Type': 'Returning'},
 39: {'Transaction_ID': 'NP00039',
      'Date': '2025-05-23',
      'City': 'Biratnagar',
      'Customer_Gender': 'Female',
      'Customer_Age': 43,
      'Product_Category': 'Groceries',
      'Product_Name': 'Tea 500g',
      'Quantity': 4,
      'Unit_Price_NPR': 420,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 1512.0,
      'Customer_Type': 'Returning'},
 40: {'Transaction_ID': 'NP00040',
      'Date': '2025-04-02',
      'City': 'Hetauda',
      'Customer_Gender': 'Female',
      'Customer_Age': 34,
      'Product_Category': 'Groceries',
      'Product_Name': 'Basmati Rice 5kg',
      'Quantity': 1,
      'Unit_Price_NPR': 850,
      'Payment_Method': 'Cash',
      'Sales_NPR': 765.0,
      'Customer_Type': 'Returning'},
 41: {'Transaction_ID': 'NP00041',
      'Date': '2025-03-01',
      'City': 'Birgunj',
      'Customer_Gender': 'Female',
      'Customer_Age': 30,
      'Product_Category': 'Groceries',
      'Product_Name': 'Tea 500g',
      'Quantity': 2,
      'Unit_Price_NPR': 420,
      'Payment_Method': 'Cash',
      'Sales_NPR': 756.0,
      'Customer_Type': 'Returning'},
 42: {'Transaction_ID': 'NP00042',
      'Date': '2025-12-10',
      'City': 'Pokhara',
      'Customer_Gender': 'Male',
      'Customer_Age': 22,
      'Product_Category': 'Electronics',
      'Product_Name': 'USB-C Charger',
      'Quantity': 2,
      'Unit_Price_NPR': 1400,
      'Payment_Method': 'Bank Transfer',
      'Sales_NPR': 2520.0,
      'Customer_Type': 'Returning'},
 43: {'Transaction_ID': 'NP00043',
      'Date': '2025-06-08',
      'City': 'Birgunj',
      'Customer_Gender': 'Male',
      'Customer_Age': 36,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Face Serum',
      'Quantity': 2,
      'Unit_Price_NPR': 1800,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 3600.0,
      'Customer_Type': 'New'},
 44: {'Transaction_ID': 'NP00044',
      'Date': '2025-11-12',
      'City': 'Hetauda',
      'Customer_Gender': 'Male',
      'Customer_Age': 53,
      'Product_Category': 'Home & Kitchen',
      'Product_Name': 'Water Bottle',
      'Quantity': 2,
      'Unit_Price_NPR': 700,
      'Payment_Method': 'Debit Card',
      'Sales_NPR': 1260.0,
      'Customer_Type': 'New'},
 45: {'Transaction_ID': 'NP00045',
      'Date': '2025-08-15',
      'City': 'Butwal',
      'Customer_Gender': 'Female',
      'Customer_Age': 50,
      'Product_Category': 'Clothing',
      'Product_Name': 'Jacket',
      'Quantity': 1,
      'Unit_Price_NPR': 5500,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 5500.0,
      'Customer_Type': 'Returning'},
 46: {'Transaction_ID': 'NP00046',
      'Date': '2025-12-06',
      'City': 'Hetauda',
      'Customer_Gender': 'Male',
      'Customer_Age': 33,
      'Product_Category': 'Sports & Fitness',
      'Product_Name': 'Yoga Mat',
      'Quantity': 2,
      'Unit_Price_NPR': 1800,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 3600.0,
      'Customer_Type': 'New'},
 47: {'Transaction_ID': 'NP00047',
      'Date': '2025-11-09',
      'City': 'Lalitpur',
      'Customer_Gender': 'Male',
      'Customer_Age': 58,
      'Product_Category': 'Clothing',
      'Product_Name': 'Kurta Set',
      'Quantity': 1,
      'Unit_Price_NPR': 3200,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 2880.0,
      'Customer_Type': 'Returning'},
 48: {'Transaction_ID': 'NP00048',
      'Date': '2025-01-03',
      'City': 'Lalitpur',
      'Customer_Gender': 'Female',
      'Customer_Age': 32,
      'Product_Category': 'Groceries',
      'Product_Name': 'Lentils 1kg',
      'Quantity': 1,
      'Unit_Price_NPR': 180,
      'Payment_Method': 'Cash',
      'Sales_NPR': 180.0,
      'Customer_Type': 'Returning'},
 49: {'Transaction_ID': 'NP00049',
      'Date': '2025-03-04',
      'City': 'Butwal',
      'Customer_Gender': 'Male',
      'Customer_Age': 47,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Face Serum',
      'Quantity': 1,
      'Unit_Price_NPR': 1800,
      'Payment_Method': 'Khalti',
      'Sales_NPR': 1620.0,
      'Customer_Type': 'Returning'},
 50: {'Transaction_ID': 'NP00050',
      'Date': '2025-09-16',
      'City': 'Birgunj',
      'Customer_Gender': 'Female',
      'Customer_Age': 53,
      'Product_Category': 'Beauty & Personal Care',
      'Product_Name': 'Moisturizer',
      'Quantity': 1,
      'Unit_Price_NPR': 950,
      'Payment_Method': 'eSewa',
      'Sales_NPR': 902.5,
      'Customer_Type': 'New'}}

